package app.pbbls.android.core.designsystem

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import java.util.Locale

// GENERATED from the M3-evo Material Theme Builder export (seed #CE7E8A,
// Material Theme Builder export 2026-09-24 12:15:20) for #853. Regenerate with the script in
// docs/superpowers/plans/2026-09-24-android-m3-expressive-theme.md (Task 1.3);
// do not hand-edit a value. This file is the only place a Color(0x…) literal
// may live outside tests — ThemeLiteralsTest enforces it from Part 7.

internal val LightScheme: ColorScheme =
    lightColorScheme(
        primary = Color(0xFF8E4955),
        surfaceTint = Color(0xFF8E4955),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DD),
        onPrimaryContainer = Color(0xFF72333E),
        secondary = Color(0xFF76565A),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DD),
        onSecondaryContainer = Color(0xFF5C3F43),
        tertiary = Color(0xFF266A4A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFACF2C8),
        onTertiaryContainer = Color(0xFF025233),
        error = Color(0xFF7F560F),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDDB2),
        onErrorContainer = Color(0xFF624000),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF22191A),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF524345),
        outline = Color(0xFF847374),
        outlineVariant = Color(0xFFD7C1C3),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDED),
        inversePrimary = Color(0xFFFFB2BC),
        primaryFixed = Color(0xFFFFD9DD),
        onPrimaryFixed = Color(0xFF3B0714),
        primaryFixedDim = Color(0xFFFFB2BC),
        onPrimaryFixedVariant = Color(0xFF72333E),
        secondaryFixed = Color(0xFFFFD9DD),
        onSecondaryFixed = Color(0xFF2C1518),
        secondaryFixedDim = Color(0xFFE5BDC1),
        onSecondaryFixedVariant = Color(0xFF5C3F43),
        tertiaryFixed = Color(0xFFACF2C8),
        onTertiaryFixed = Color(0xFF002112),
        tertiaryFixedDim = Color(0xFF91D5AD),
        onTertiaryFixedVariant = Color(0xFF025233),
        surfaceDim = Color(0xFFE7D6D7),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F1),
        surfaceContainer = Color(0xFFFBEAEB),
        surfaceContainerHigh = Color(0xFFF6E4E5),
        surfaceContainerHighest = Color(0xFFF0DEDF),
    )

internal val LightMediumContrastScheme: ColorScheme =
    lightColorScheme(
        primary = Color(0xFF5D222E),
        surfaceTint = Color(0xFF8E4955),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA05863),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF4A2F33),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF866569),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF003F26),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF377957),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF4C3100),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF90651E),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF170F10),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF403334),
        outline = Color(0xFF5E4F50),
        outlineVariant = Color(0xFF7A696A),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDED),
        inversePrimary = Color(0xFFFFB2BC),
        primaryFixed = Color(0xFFA05863),
        onPrimaryFixed = Color(0xFFFFFFFF),
        primaryFixedDim = Color(0xFF83404C),
        onPrimaryFixedVariant = Color(0xFFFFFFFF),
        secondaryFixed = Color(0xFF866569),
        onSecondaryFixed = Color(0xFFFFFFFF),
        secondaryFixedDim = Color(0xFF6B4D51),
        onSecondaryFixedVariant = Color(0xFFFFFFFF),
        tertiaryFixed = Color(0xFF377957),
        onTertiaryFixed = Color(0xFFFFFFFF),
        tertiaryFixedDim = Color(0xFF1A6040),
        onTertiaryFixedVariant = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD3C3C4),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F1),
        surfaceContainer = Color(0xFFF6E4E5),
        surfaceContainerHigh = Color(0xFFEAD9DA),
        surfaceContainerHighest = Color(0xFFDECECF),
    )

internal val LightHighContrastScheme: ColorScheme =
    lightColorScheme(
        primary = Color(0xFF501824),
        surfaceTint = Color(0xFF8E4955),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF753540),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF3E2529),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF5F4145),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF00341F),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF075435),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF3F2700),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF654200),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFF3DDDF),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF36292A),
        outlineVariant = Color(0xFF544547),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFB2BC),
        primaryFixed = Color(0xFF753540),
        onPrimaryFixed = Color(0xFFFFFFFF),
        primaryFixedDim = Color(0xFF591F2B),
        onPrimaryFixedVariant = Color(0xFFFFFFFF),
        secondaryFixed = Color(0xFF5F4145),
        onSecondaryFixed = Color(0xFFFFFFFF),
        secondaryFixedDim = Color(0xFF462B2F),
        onSecondaryFixedVariant = Color(0xFFFFFFFF),
        tertiaryFixed = Color(0xFF075435),
        onTertiaryFixed = Color(0xFFFFFFFF),
        tertiaryFixedDim = Color(0xFF003B24),
        onTertiaryFixedVariant = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFC5B5B6),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFEEDED),
        surfaceContainer = Color(0xFFF0DEDF),
        surfaceContainerHigh = Color(0xFFE1D0D1),
        surfaceContainerHighest = Color(0xFFD3C3C4),
    )

internal val DarkScheme: ColorScheme =
    darkColorScheme(
        primary = Color(0xFFFFB2BC),
        surfaceTint = Color(0xFFFFB2BC),
        onPrimary = Color(0xFF561D28),
        primaryContainer = Color(0xFF72333E),
        onPrimaryContainer = Color(0xFFFFD9DD),
        secondary = Color(0xFFE5BDC1),
        onSecondary = Color(0xFF43292D),
        secondaryContainer = Color(0xFF5C3F43),
        onSecondaryContainer = Color(0xFFFFD9DD),
        tertiary = Color(0xFF91D5AD),
        onTertiary = Color(0xFF003822),
        tertiaryContainer = Color(0xFF025233),
        onTertiaryContainer = Color(0xFFACF2C8),
        error = Color(0xFFF3BD6E),
        onError = Color(0xFF442B00),
        errorContainer = Color(0xFF624000),
        onErrorContainer = Color(0xFFFFDDB2),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFF0DEDF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFD7C1C3),
        outline = Color(0xFF9F8C8E),
        outlineVariant = Color(0xFF524345),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF382E2F),
        inversePrimary = Color(0xFF8E4955),
        primaryFixed = Color(0xFFFFD9DD),
        onPrimaryFixed = Color(0xFF3B0714),
        primaryFixedDim = Color(0xFFFFB2BC),
        onPrimaryFixedVariant = Color(0xFF72333E),
        secondaryFixed = Color(0xFFFFD9DD),
        onSecondaryFixed = Color(0xFF2C1518),
        secondaryFixedDim = Color(0xFFE5BDC1),
        onSecondaryFixedVariant = Color(0xFF5C3F43),
        tertiaryFixed = Color(0xFFACF2C8),
        onTertiaryFixed = Color(0xFF002112),
        tertiaryFixedDim = Color(0xFF91D5AD),
        onTertiaryFixedVariant = Color(0xFF025233),
        surfaceDim = Color(0xFF1A1112),
        surfaceBright = Color(0xFF413738),
        surfaceContainerLowest = Color(0xFF140C0D),
        surfaceContainerLow = Color(0xFF22191A),
        surfaceContainer = Color(0xFF261D1E),
        surfaceContainerHigh = Color(0xFF312829),
        surfaceContainerHighest = Color(0xFF3D3233),
    )

internal val DarkMediumContrastScheme: ColorScheme =
    darkColorScheme(
        primary = Color(0xFFFFD1D6),
        surfaceTint = Color(0xFFFFB2BC),
        onPrimary = Color(0xFF48121E),
        primaryContainer = Color(0xFFC97A86),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0xFFFCD2D6),
        onSecondary = Color(0xFF371F22),
        secondaryContainer = Color(0xFFAC888C),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFA6EBC2),
        onTertiary = Color(0xFF002C1A),
        tertiaryContainer = Color(0xFF5C9E79),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFFFD69E),
        onError = Color(0xFF362100),
        errorContainer = Color(0xFFB8883F),
        onErrorContainer = Color(0xFF000000),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFEDD7D9),
        outline = Color(0xFFC1ADAF),
        outlineVariant = Color(0xFF9E8C8D),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF312829),
        inversePrimary = Color(0xFF73343F),
        primaryFixed = Color(0xFFFFD9DD),
        onPrimaryFixed = Color(0xFF2C000B),
        primaryFixedDim = Color(0xFFFFB2BC),
        onPrimaryFixedVariant = Color(0xFF5D222E),
        secondaryFixed = Color(0xFFFFD9DD),
        onSecondaryFixed = Color(0xFF200B0E),
        secondaryFixedDim = Color(0xFFE5BDC1),
        onSecondaryFixedVariant = Color(0xFF4A2F33),
        tertiaryFixed = Color(0xFFACF2C8),
        onTertiaryFixed = Color(0xFF00150A),
        tertiaryFixedDim = Color(0xFF91D5AD),
        onTertiaryFixedVariant = Color(0xFF003F26),
        surfaceDim = Color(0xFF1A1112),
        surfaceBright = Color(0xFF4D4243),
        surfaceContainerLowest = Color(0xFF0C0607),
        surfaceContainerLow = Color(0xFF241B1C),
        surfaceContainer = Color(0xFF2F2526),
        surfaceContainerHigh = Color(0xFF3A3031),
        surfaceContainerHighest = Color(0xFF463B3C),
    )

internal val DarkHighContrastScheme: ColorScheme =
    darkColorScheme(
        primary = Color(0xFFFFEBED),
        surfaceTint = Color(0xFFFFB2BC),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFFFACB7),
        onPrimaryContainer = Color(0xFF210006),
        secondary = Color(0xFFFFEBED),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFE1B9BD),
        onSecondaryContainer = Color(0xFF190609),
        tertiary = Color(0xFFBBFFD6),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFF8DD1A9),
        onTertiaryContainer = Color(0xFF000E06),
        error = Color(0xFFFFEDD9),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFEFB96B),
        onErrorContainer = Color(0xFF130900),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDF),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFFFFFFF),
        outline = Color(0xFFFFEBED),
        outlineVariant = Color(0xFFD3BEBF),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF0DEDF),
        inverseOnSurface = Color(0xFF000000),
        inversePrimary = Color(0xFF73343F),
        primaryFixed = Color(0xFFFFD9DD),
        onPrimaryFixed = Color(0xFF000000),
        primaryFixedDim = Color(0xFFFFB2BC),
        onPrimaryFixedVariant = Color(0xFF2C000B),
        secondaryFixed = Color(0xFFFFD9DD),
        onSecondaryFixed = Color(0xFF000000),
        secondaryFixedDim = Color(0xFFE5BDC1),
        onSecondaryFixedVariant = Color(0xFF200B0E),
        tertiaryFixed = Color(0xFFACF2C8),
        onTertiaryFixed = Color(0xFF000000),
        tertiaryFixedDim = Color(0xFF91D5AD),
        onTertiaryFixedVariant = Color(0xFF00150A),
        surfaceDim = Color(0xFF1A1112),
        surfaceBright = Color(0xFF594D4E),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF261D1E),
        surfaceContainer = Color(0xFF382E2F),
        surfaceContainerHigh = Color(0xFF43393A),
        surfaceContainerHighest = Color(0xFF4F4445),
    )

/**
 * Ink for the Google sign-in capsule, which is a pinned white surface under
 * Google's branding rules and must not follow the theme (the old iOS
 * `onLight` token). 11.2:1 on white.
 */
internal val GoogleCapsuleInk = Color(0xFF4A3639)

/** One of the six static schemes. Wallpaper schemes bypass this entirely. */
internal fun pebblesColorScheme(
    dark: Boolean,
    contrast: ContrastLevel,
): ColorScheme =
    when (contrast) {
        ContrastLevel.STANDARD -> if (dark) DarkScheme else LightScheme
        ContrastLevel.MEDIUM -> if (dark) DarkMediumContrastScheme else LightMediumContrastScheme
        ContrastLevel.HIGH -> if (dark) DarkHighContrastScheme else LightHighContrastScheme
    }

// Hand-written, not from the export: the generator script emits this block
// verbatim so a regeneration keeps it. Keep the two in step.

/** `#RRGGBB`, alpha dropped — the SVG pipeline misparses 8-digit hex. */
internal fun Color.toRgbHex(): String = String.format(Locale.ROOT, "#%06X", toArgb() and 0xFFFFFF)
