package app.pbbls.android.core.designsystem

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import app.pbbls.android.testing.AA_NON_TEXT
import app.pbbls.android.testing.AA_TEXT
import app.pbbls.android.testing.contrastRatio
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Every foreground/ground pair the app draws, across all six schemes (#853).
 * Dynamic (wallpaper) schemes are generated by the OS and are not ours to test.
 */
class ColorSchemeContrastTest {
    private val schemes: List<Pair<String, ColorScheme>> =
        ContrastLevel.entries.flatMap { level ->
            listOf(
                "light/$level" to pebblesColorScheme(dark = false, contrast = level),
                "dark/$level" to pebblesColorScheme(dark = true, contrast = level),
            )
        }

    private fun ColorScheme.onPairs(): List<Triple<String, Color, Color>> =
        listOf(
            Triple("onPrimary/primary", onPrimary, primary),
            Triple("onPrimaryContainer/primaryContainer", onPrimaryContainer, primaryContainer),
            Triple("onSecondary/secondary", onSecondary, secondary),
            Triple("onSecondaryContainer/secondaryContainer", onSecondaryContainer, secondaryContainer),
            Triple("onTertiary/tertiary", onTertiary, tertiary),
            Triple("onTertiaryContainer/tertiaryContainer", onTertiaryContainer, tertiaryContainer),
            Triple("onError/error", onError, error),
            Triple("onErrorContainer/errorContainer", onErrorContainer, errorContainer),
            Triple("inverseOnSurface/inverseSurface", inverseOnSurface, inverseSurface),
        )

    private fun ColorScheme.grounds(): List<Pair<String, Color>> =
        listOf(
            "surface" to surface,
            "surfaceContainerLowest" to surfaceContainerLowest,
            "surfaceContainerLow" to surfaceContainerLow,
            "surfaceContainer" to surfaceContainer,
            "surfaceContainerHigh" to surfaceContainerHigh,
            "surfaceContainerHighest" to surfaceContainerHighest,
        )

    private fun ColorScheme.inks(): List<Pair<String, Color>> =
        listOf("onSurface" to onSurface, "onSurfaceVariant" to onSurfaceVariant, "primary" to primary, "error" to error)

    @Test
    fun `every on-colour is AA on its container`() {
        val failures =
            schemes.flatMap { (name, scheme) ->
                scheme.onPairs().mapNotNull { (pair, ink, ground) ->
                    val ratio = contrastRatio(ink, ground)
                    "$name $pair = $ratio".takeIf { ratio < AA_TEXT }
                }
            }
        assertTrue("below AA:\n" + failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun `text inks are AA on every surface step`() {
        val failures =
            schemes.flatMap { (name, scheme) ->
                scheme.inks().flatMap { (inkName, ink) ->
                    scheme.grounds().mapNotNull { (groundName, ground) ->
                        val ratio = contrastRatio(ink, ground)
                        "$name $inkName/$groundName = $ratio".takeIf { ratio < AA_TEXT }
                    }
                }
            }
        assertTrue("below AA:\n" + failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun `outline is AA for non-text on surface`() {
        val failures =
            schemes.mapNotNull { (name, scheme) ->
                val ratio = contrastRatio(scheme.outline, scheme.surface)
                "$name outline/surface = $ratio".takeIf { ratio < AA_NON_TEXT }
            }
        assertTrue("below 3:1:\n" + failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun `contrast levels map from the system float`() {
        assertTrue(ContrastLevel.fromSystemContrast(0f) == ContrastLevel.STANDARD)
        assertTrue(ContrastLevel.fromSystemContrast(-1f) == ContrastLevel.STANDARD)
        assertTrue(ContrastLevel.fromSystemContrast(0.5f) == ContrastLevel.MEDIUM)
        assertTrue(ContrastLevel.fromSystemContrast(1f) == ContrastLevel.HIGH)
    }
}
