import Testing
@testable import Pebbles

/// The artworks are generated by `Scripts/valence-art-to-svg.mjs` and
/// committed, so nothing at build time would notice if a file went missing or
/// the script changed its output shape — the picker would just render nine
/// empty stones. These are that alarm.
@Suite("ValenceArt")
struct ValenceArtTests {

    @Test("every valence has artwork that parses and wobbles")
    func everyValenceHasArt() {
        for valence in Valence.allCases {
            let art = ValenceArt.art(for: valence)
            #expect(art != nil, "no artwork for \(valence)")
            #expect(art?.ink.isEmpty == false, "no ink for \(valence)")
            #expect(art?.viewBox.width ?? 0 > 0, "degenerate viewBox for \(valence)")
        }
    }

    /// The fossil's spiral is the one filled region in each artwork. Inked as a
    /// centerline it fills in solid and reads as a blob, so losing the fill
    /// classification is a real (and quiet) regression.
    @Test("every artwork keeps its filled region")
    func everyArtworkHasAFilledRegion() {
        for valence in Valence.allCases {
            let regions = ValenceArt.art(for: valence)?.regions ?? []
            #expect(regions.count == 1, "expected one filled region for \(valence), got \(regions.count)")
            #expect(regions.first?.path.isEmpty == false, "empty region for \(valence)")
        }
    }

    @Test("art is cached, not rebuilt")
    func artIsCached() {
        for valence in Valence.allCases {
            #expect(ValenceArt.art(for: valence) === ValenceArt.art(for: valence))
        }
    }
}
